name: calliope-dashboard-070
channels:
  - conda-forge/label/calliope_dev
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - calliope=0.7.0dev7
  - coin-or-cbc=2.10
  - dash=3.2.0
  - dash-leaflet=1.0.15
  - plotly=6.3.0
  # Required for inline Plotly rendering in Jupyter/PyCharm notebooks.
  - nbformat>=4.2
  - pandas=2.1.4
  - numpy=1.26.4
  - xarray=2024.3.0
  - netcdf4=1.7.4
  - h5netcdf=1.8.1
  - pytest=8.3
